### ISSUE TITLE
Missing dependencies

### ISSUE THREAD

**Issue by tsauvajon** [koltyakov/pnp-upload#2]
I am trying to use your repo but I was not able to compile it.
I've globally installed two missing dependencies (tsc and electron), but it still won't compile:
```
error TS5023: Unknown compiler option 'lib'.
error TS5023: Unknown compiler option 'moduleResolution'.
error TS5023: Unknown compiler option 'skipLibCheck'.
error TS5023: Unknown compiler option 'types'.
```

What version of `tsc` are you using for this project?

**Comment by koltyakov** [comment]
It compiles just fine for me. No global dependencies are required at all.
When running `tsc -p .` from an npm task a locally installed TypeScript and compiler are used (`/node_modules/.bin/tsc`). Seems like you run `tsc` in the console and an old TypeScript version is installed which "doesn't know" what these options are.
Electron is also not required optional dependency which is used by another dependency for On-Demand auth only.

**Comment by tsauvajon** [comment]
You are completely right about tsc.
The problem was with my build script (I incorrectly adapted it to run on Windows).

I am still getting the following error message when running the project and using the `OnDemandCredentials` strategy:
```
'electron' is not recognized as an internal or external command
```

**Comment by koltyakov** [comment]
What version of SharePoint are you targeting to?

**Comment by tsauvajon** [comment]
I'm using SharePoint Online (Office 365)

**Comment by tsauvajon** [comment]
Just to make sure I'm doing it correctly - I'm trying to upload a file in a library.
The URL I'm using looks like:
https://[company].sharepoint.com/sites/[team-site]/[Library name]/Forms/AllItems.aspx

**Comment by koltyakov** [comment]
This is obviously an incorrect URL and the cause of the issue. This is a URL to a view page but not a folder. Should be just `/sites/[team-site]/[Library name]` for root folder in a lib and `/sites/[team-site]/[Library name]/[Folder]/[Sub Folder]`.

**Comment by tsauvajon** [comment]
Thanks again for your help; how are you supposed to get the correct URL in the first place?
I just tried to use `/sites/[team-site]/[Library name]`, which returns a 404. 
I tried creating a folder in the lib, used `/sites/[team-site]/[Library name]/[Folder], same issue.

I realise this is not a helpdesk nor a problem with your repo so thanks again for the time you've spent answering my newbie questions.

**Comment by koltyakov** [comment]
In SharePoint API terms it is `ServerRelativeUrl` property.
In practice, you just taking parts from the URL of the view (lib root folder) and folder's relative path.

![image](https://user-images.githubusercontent.com/7816483/59688223-efe7e080-91e5-11e9-9459-1fa5368ae915.png)
